version: '3.5'

services:
  symfony-blog:
    container_name: symfony-blog
    build:
      context: ./docker
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    environment:
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      PHP_IDE_CONFIG: serverName=symfony-server
    ports:
      - '1000:8000'
    networks:
      - symfony-network
    depends_on:
      - symfony-mariadb

  symfony-mariadb:
    container_name: symfony-mariadb
    image: mariadb:10.11.4
    ports:
      - '3336:3306'
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - symfony-mariadb-data:/var/lib/mysql
    networks:
      - symfony-network

networks:
  symfony-network:

volumes:
  symfony-mariadb-data:
